<a href="https://colab.research.google.com/github/Chaerim0626/deeplearning-study/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%EC%8B%A4%EC%8A%B5(23_03_03_01%2C_%EC%9D%B4%EB%A6%84__%EB%B0%95%EC%B1%84%EB%A6%BC)_NumPy_Arrays_(Part_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Arrays - Part 1<br>

by uramoon@kw.ac.kr <br>
원본 출처: https://www.learnpython.org/ (<a href="https://raw.githubusercontent.com/ronreiter/interactive-tutorials/master/LICENSE">Apache 2.0 License</a>)

## 리스트로부터 배열 생성
NumPy 배열은 파이썬 리스트와 비슷하지만 전체 원소에 대해 계산을 수행할 때 
빠릅니다.

In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [3]:
cd /content/drive/MyDrive/Colab Notebooks/Github

/content/drive/MyDrive/Colab Notebooks/Github


In [ ]:
# 키와 몸무게 리스트
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# NumPy 사용시 필요한 것
import numpy as np

# 리스트를 NumPy 배열로 변환하는 방법
np_height = np.array(height)
np_weight = np.array(weight)

In [ ]:
# 키 리스트의 내용과 타입 확인
print(height)
print(type(height))

[1.87, 1.87, 1.82, 1.91, 1.9, 1.85]
<class 'list'>


***TODO: 키 배열의 내용과 타입을 출력해보세요.***




In [ ]:
# TODO
print(np_height)
print(type(np_height))

[1.87 1.87 1.82 1.91 1.9  1.85]
<class 'numpy.ndarray'>


## 원소별 계산<br>
체질량지수 (BMI) 계산을 해봅시다. (체중 / 키^2)<br>
18.5 이하 저체중, 18.5 ~ 25 정상, 25 이상 과체중

In [ ]:
# BMI 계산하여 리스트에 저장하기
bmi = [] # BMI를 저장할 빈 리스트 생성

for i in range(len(height)):
  bmi.append(weight[i] / height[i] ** 2)

print(bmi)
print(type(bmi))

[23.349252194801107, 27.887557550973714, 28.755585074266392, 25.48723993311587, 23.87257617728532, 25.843681519357194]
<class 'list'>


In [ ]:
# BMI 계산하여 NumPy 배열에 저장하기
np_bmi = np.array(bmi)
# Calculate bmi
np_bmi = np_weight / np_height ** 2

# Print the result
print(np_bmi)
print(type(np_bmi))

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
<class 'numpy.ndarray'>


BMI 계산 시 위의 두 방식 중 어떤 것이 편한가요? 대용량 데이터 처리 시 속도는 NumPy가 확실히 빠릅니다.

다음으로 리스트와 NumPy의 덧셈을 비교해봅시다.

In [ ]:
# 리스트 덧셈
print(weight + height)

# NumPy 배열 덧셈
print(np_weight + np_height)

[81.65, 97.52, 95.25, 92.98, 86.18, 88.45, 1.87, 1.87, 1.82, 1.91, 1.9, 1.85]
[83.52 99.39 97.07 94.89 88.08 90.3 ]


***TODO: 덧셈이 어떻게 수행되는지 아래에 적으세요.***

1. 리스트: 원래 리스트에 새로운 리스트 내용들이 추가됩니다.
2. NumPy 배열: 원래 리스트 원소들이 새로운 리스트의 원소들과 더해진 리스트가 생성됩니다.

## 원소 추려내기

***TODO: BMI 리스트에서 원소 추려내기 (NumPy 사용 금지)***

In [ ]:
# TODO1: 각 인덱스의 BMI가 25보다 큰지 아닌지가 저장된 리스트를 만들어 출력하세요.
# 예: [False, True, ...]
result1 = [False]*len(bmi)
for i in range(len(bmi)):
    if bmi[i]>25: result1[i]=True
print(result1)

# TODO2: 25보다 큰 값의 BMI를 리스트로 만들어 출력하세요.
# 예: [27.8876, 28.7556, ...]
result2 = []
for i in range(len(result1)):
    if result1[i]==True:
        result2.append(bmi[i])
print(result2)

[False, True, True, True, False, True]
[27.887557550973714, 28.755585074266392, 25.48723993311587, 25.843681519357194]


NumPy를 사용하면 아래와 같이 간단합니다!

In [ ]:
# For a boolean response
print(np_bmi > 25)

# Print only those observations above 25
np_bmi[np_bmi > 25]

[False  True  True  True False  True]


array([27.88755755, 28.75558507, 25.48723993, 25.84368152])